"""empty message

Revision ID: 962bcd6cf172
Revises: 95147ee0c62d
Create Date: 2019-07-16 06:37:23.612877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962bcd6cf172'
down_revision = '95147ee0c62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ninjas', 'dojo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'ninjas', 'dojos', ['dojo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ninjas', type_='foreignkey')
    op.alter_column('ninjas', 'dojo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
